# Generated by Django 5.2.7 on 2026-01-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='resume',
        ),
    ]
