# Generated by Django 5.2.7 on 2026-01-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employeeprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
